[package]
name = "notia_analyzer"
version = "0.1.0"
edition = "2021"

[lib]
name = "notia_analyzer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
regex = "1.11.2"
